### ISSUE TITLE
Parse Biscuit without public key

### ISSUE THREAD

**Issue by Stephen-Hilton** [biscuit-auth/biscuit-python#10]
First, this is a great project, thank you for pulling this together!   It has solved all my use-cases except one:

I don't see how to parse a biscuit without a public key.   This is NOT to authorize, but just to inspect / parse...  i.e., the way [biscuitsec.org](https://www.biscuitsec.org/) does on their home page.   Paste a biscuit into their webpage, and it will decode and display.   So... this is possible, just not seeing how. 

For example, this biscuit:
`EvoBCo8BCg90ZXN0OmNhcGFiaWxpdHkKBkRFTEVURQoWbmFtZXNwYWNlLnNvbWVyZXNvdXJjZQoGSU5TRVJUCgZTRUxFQ1QKBlVQREFURRgDIg8KDQiACBIDGIEIEgMYgggiDwoNCIAIEgMYgwgSAxiCCCIPCg0IgAgSAxiECBIDGIIIIg8KDQiACBIDGIUIEgMYgggSJAgAEiBuhGUKrI9PAHllP7i97pRKuR3MMUYyf68OhqETL2SU-xpAx3EWdjFsaf2mOgU6Lt_VjM1HGTx1wBlwS8EtbWZJtiHQJuTVdpNP279mcPf9XDfs9mIP2Z-P-Iu9Ap6AJ4dmAiIiCiC60io01fNSwbqge12r_s5rD9IzVI70vcFoGvkaq_dqkw==`

decodes to this list of facts:
```
test:capability("DELETE", "namespace.someresource");
test:capability("INSERT", "namespace.someresource");
test:capability("SELECT", "namespace.someresource");
test:capability("UPDATE", "namespace.someresource");
```

Thoughts?   Thx!

**Comment by divarvel** [comment]
You're right, it is not exposed in the python library yet.

If you're willing to try, it's a matter of exposing methods from `UnverifiedBiscuit`.
For now, a workaround would be to shell out to biscuit-cli

**Comment by divarvel** [comment]
Else, I'll have a look this week

**Comment by divarvel** [comment]
I have started working on it in #11 would that solve your issue?

**Comment by Stephen-Hilton** [comment]
Looks good, thanks for the new feature!

**Comment by divarvel** [comment]
I have released a version containing the changes

https://pypi.org/project/biscuit-python/0.2.1/

**Comment by Stephen-Hilton** [comment]
Thank you!!   I will update our SDK shortly.

Appreciate the assistance!

Stephen
